{% set name = "hyppo" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neurodata/hyppo/archive/v{{ version }}.tar.gz
  sha256: a7e57f420813bb80e515b01ba3cdaf50f3e2c1672e6c1b2dbeb21f4e60a29847

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.17
    - scipy >=1.4.0
    - numba >=0.46
    - scikit-learn >=0.19.1
    - autograd >=1.3

test:
  imports:
    - hyppo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://hyppo.neurodata.io/
  dev_url: https://github.com/neurodata/hyppo
  summary: A comprehensive independence testing package
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
    - jan-janssen
